### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by vladfrangu** [devsnek/snekfetch#9]
One: Why are you requireing "stream" twice?
Two: Wasn't that _getHeader hotfix merged? Is it still needed?
Two.1: Under _addFinalHeaders, is the get case sensitive? https://github.com/devsnek/snekfetch/blob/bca7b089e562c2e5cdbd22fc62655e1fb5c3fa55/src/index.js#L290-L292
Three: How does followRedirects work? Am dum and don't understand, how can we see the chain of redirects?

**Comment by devsnek** [comment]
1. handling webpack dependency chain calls
2. just because something is merged doesn't mean everyone has it
  2.1. headers are always stored lowercase so you don't have to guess how to get them
3. it doesn't keep a trace of which urls it pings around. if you need to keep a chain you should do it yourself.
